apiVersion: v1
kind: Pod
metadata:
  name: mynginx-pod
  labels: 
    app: myapp
spec:
 containers:
   - name: mynginx-c
     image: nginx:latest
     ports:
      - name: httpd
        containerPort: 80